#!/bin/bash -e
## Check if we're on a remote tracking branch

## read input, display help if necessary
if [[ "$@" == *--help* ]]; then
    cat<<EOF
 Check for a remote tracking branch

 This command checks whether the repository is on a remote tracking
 branch. Otherwise an error is raised.
 Does not raise an error if the repository is in detached HEAD mode 
 and there are no new commits.

 Usage:
    git check-branch
EOF
    exit 0;
fi

if [[ $(cat .git/HEAD | cut -c1-4) != "ref:" ]]; then
    ## detached head cannot be remote tracking branch...
    ## ...but: if there are no new commits, we can safely ignore this
    ## FIXME: this test only succeed if the new commit is actually
    ##        checked out
    if [[ $(git diff origin...  --quiet || echo "FAIL") == "FAIL" ]]; then
	echo "Error in $PWD:"
	echo " Detached head and new commits. Attach the HEAD by creating"
        echo " a new branch or risk losing the commits."
	exit 1
    fi
    echo "Warning in $PWD:"
    echo " Detached head. This probably just mean that there are updates available"
    echo " that are not yet used. To update to the most recent version, use "
    echo "   git checkout <branchname> "
    echo " To list all branches, use "
    echo "   git branch -a "
    echo " Alternatively try to use \"git attach-head\" or \"git rpull\" to update submodule."
    exit 0
fi

tmp=`git branch --no-color -vv 2> /dev/null`
while read line; do
    if [[ "${line:0:1}" != "*" ]]; then
	continue
    fi
    #echo "$line"
    remote=`expr "$line" : '.*\[\(.*\)\]'` || nontracking=0
done <<< "$tmp"

activebranch=`git name-rev --name-only HEAD`

if [[ "$nontracking" ]]; then
    ## if we're here: fail
    echo "Error in $PWD:"
    echo " Branch \"$activebranch\" is not a remote tracking branch."
    exit 1
fi
