#!/bin/bash -e
## Check if we're on a remote tracking branch

while read line; do
    if [[ "${line:0:1}" != "*" ]]; then
	continue
    fi
    ##echo "$line"
    remote=`expr "$line" : '.*\[\(.*\)\]'` || nontracking=0
done < <(git branch --no-color -vv 2> /dev/null)

activebranch=`git name-rev --name-only HEAD`

if [[ "$nontracking" ]]; then
    ## if we're here: fail
    echo "Error in $PWD:"
    if [[ "$activebranch" =~ "~" ]]; then
	echo " Detached head. Use git attach-head or git pull to update submodule."
    else
	echo " Branch \"$activebranch\" is not a remote tracking branch."
    fi
    exit 1
fi
