#!/bin/bash -e
## Recursive clone
## clone into $2 directory
## and attach heads.

if [[ "$2" ]]; then
    name="$2"
else
    name=`basename "$1"`
    name=${name%.git}
fi

echo "Cloning into $name..."
git clone --recursive -q "$1" "$name" > /dev/null
echo "done."
cd "$name"
## attach heads
if [ -f .gitmodules ]; then
    echo "Attaching heads of submodules..."
    git submodule --quiet foreach --recursive git attach-head -w
    echo "done."
fi