#!/bin/bash -e
## Do a conditional push: only push, if remotes are behind
## otherwise accept the same arguments as push

tmp=`git branch --no-color -vv 2> /dev/null`
while read line; do
    if [[ "${line:0:1}" != "*" ]]; then
	continue
    fi
    ##echo "$line"
    branch=`expr "$line" : '\** *\([^ ]*\)'`
    ##echo "$branch"
    remote=`expr "$line" : '.*\[\(.*\)\]'` || continue
    ##echo "$remote"
    ## if we're ahead: branch will show it after ":" 
    status=`expr "$remote" : '.*: ahead \(.*\)'` || continue
    ##echo "$status"
    unpushed=" Branch \"$branch\" is ahead by $status commit(s)."
done <<< "$tmp"

if [ "$unpushed" ]; then
    echo "Pushing $PWD:"
    git push "$@"
fi
