#!/bin/bash
#
# Block commits that reference an unpushed commit 
# from entering the repository. We can only check references
# to commits in some local repository.
#
# The script only works if the url of a submodule contains
# the hostname, see below.
#
# Configuration:
hostname=$(hostname)
repobase="/scratch/git-sfs/"
#

## Fail on first error
set -e

# --- Command line
refname="$1"
oldrev="$2"
newrev="$3"

# --- Safety check
if [ -z "$GIT_DIR" ]; then
	echo "Don't run this script from the command line." >&2
	echo " (if you want, you could supply GIT_DIR then run" >&2
	echo "  $0 <ref> <oldrev> <newrev>)" >&2
	exit 1
fi

if [ -z "$refname" -o -z "$oldrev" -o -z "$newrev" ]; then
	echo "Usage: $0 <ref> <oldrev> <newrev>" >&2
	exit 1
fi

#echo "$refname $oldrev $newrev"

## --- Get submodule commits in <newrev>
commits=$(git ls-tree -r "$newrev" | grep ^160000 || echo "FAIL")

if [[ "$commits" == "FAIL" ]]; then
    ## there are no submodules
    exit 0;
fi

## --- Check if commit exists for each submodule
while read line; do
    #echo "Reading $line"
    ## format of a line: <mode> SP <type> SP <object> TAB <file>
    commit=$(expr "$line" : '.* \(.*\)	')
    #echo "Commit: $commit"
    rpath=$(expr "$line" : '.*	\(.*\)')
    ## replace / by \/
    path=${rpath/\//\\/}
    #echo "Path: $path"
    ## get repository associated with $path
    url=$(git show "$newrev:.gitmodules" | awk "/path = $path\$/{getline;print }")
    ## remove url = 
    url=${url#*url = }
    #echo "Url: $url"
    ## Format of url: user@server:repo
    if [[ $url =~ $hostname ]]; then
	repo="$repobase"${url#*:}
	#echo "Repo: $repo"
    else
        #url is relative to this repo
        repo=$(cd "$GIT_DIR/$url"; pwd)          
    fi
    if [[ -d "$repo" ]]; then
        ## The following should work, but doesn't on the server
	#GIT_DIR=$repo git rev-parse --quiet --verify $commit > /dev/null
	## so do the following instead
	if [[ "$(GIT_DIR=$repo git merge-base $commit HEAD || echo FAIL)" == "FAIL" ]]; then
	    cat<<EOF
 Error: Cannot find commit for submodule "$rpath".
 Did you use git push instead of git rpush?
 Try again with git rpush.
EOF
	    exit 1
	fi
    else 
	cat<<EOF
 Error: Cannot find submodule repository "$rpath".
 The repository "$repo" does not exist.
EOF
	exit 1
    fi
done <<< "$commits"

# --- Finished
exit 0
